# -*- coding: utf-8 -*-
"""DB이관.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nR-ak_oi6p-ZTsGrf0EPrM-770UKnnrL
"""

import pandas as pd
from sqlalchemy import create_engine
import os

# MySQL 서버 정보
user = 'kopouser'
password = '1234'
host = '유동 AWS IP주소입력'
port = 3306  # 문자열이 아닌 정수형으로 명시
database = 'kopo'

# CSV 파일 경로 리스트 (Ubuntu 환경의 실제 경로로 수정!)
csv_files = ['/home/ubuntu/pywork/codeset/account_output.csv',
             '/home/ubuntu/pywork/codeset/transaction_output.csv']

def csv_to_mysql_sequential(csv_files, user, password, host, port, database):
    """여러 CSV 파일을 순서대로 읽어 각각의 테이블에 저장하는 함수 (Ubuntu 환경용)"""
    engine = create_engine(f'mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}')

    for csv_file in csv_files:
        try:
            df = pd.read_csv(csv_file, encoding='utf-8')
            table_name = os.path.splitext(os.path.basename(csv_file))[0]  # 파일 이름 (확장자 제외)을 테이블 이름으로 사용
            df.to_sql(name=table_name, con=engine, if_exists='replace', index=False)
            print(f"'{csv_file}' 파일의 데이터를 '{table_name}' 테이블에 성공적으로 저장했습니다.")
        except FileNotFoundError:
            print(f"오류: '{csv_file}' 파일을 찾을 수 없습니다. 파일 경로를 확인하세요.")
        except Exception as e:
            print(f"오류: '{csv_file}' 파일을 처리하는 중 오류 발생: {e}")

if __name__ == "__main__":
    csv_to_mysql_sequential(csv_files, user, password, host, port, database)